### PR TITLE
Group build related commands

### PR DESCRIPTION
**Pull request by scothis**
Application, container, function and credential are now under the build
command package. This separates them from machinery commands like docs
and completion.

### CODE REVIEW

**Comment by sbawaska** [comment]
I'm not sure about the name "build". Should we leave these commands in "riff" and move docs and completion to a new package?

**Comment by scothis** [comment]
@sbawaska these CRDs are in the build.projectriff.io API group. The organization in this PR is 100% internal and is not visible to the user.

**Comment by sbawaska** [comment]
> these CRDs are in the build.projectriff.io API group.

that helps!

**Comment by scothis** [comment]
Merged as 2fd8143be62e33927b7d74b4869c008523c8e158

**Pull request closed without merging**
